spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db?useLegacyDatetimeCode=false&serverTimezone=UTC
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  key: ymLTU8rq83j4fmJZj60wh4OrMNuntIj4fmJ